api: 
  url: https://xxx.contrastsecurity.com/Contrast
  api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  service_key: XXXXXXXXXXXXXXXX
  user_name: agent_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX@Org

application:
  name: NodeGoat
  tags: Docker, Port:4000

server:
  name: Docker_alpine

