version: "3.7"

services:
  web:
    build: .
    container_name: nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm run contrast; do sleep 2; done"
    ports:
      - "4000:4000"

  mongo:
    image: mongo:latest
    container_name: mongo
    user: mongodb
    expose:
      - 27017

